### PR TITLE
Update GCI-STUDENTS.txt

### PR DESCRIPTION
**Pull request by songokucadic1423**
I added a new name

### CODE REVIEW

**Comment by canihavesomecoffee** [comment]
Hi @songokucadic1423, there seems to be a conflict with your PR and some others that were merged in the meanwhile. Could you please correct this, and then don't forget to submit for review on the GCi site (including the link to this PR)? That's the only way we can validate and approve the task 👍

**Comment by songokucadic1423** [comment]
@canihavesomecoffee done

**Comment by songokucadic1423** [comment]
@canihavesomecoffee i have done!

**Comment by songokucadic1423** [comment]
I HAVE JUST FIX IT

**Comment by Emekaborisama** [comment]
Emeka boris ama

**Pull request merged**
