### PR TITLE
update GCI-STUDENTS.txt

### PR DESCRIPTION
**Pull request by Xu-Zijun**
I am adding my anagram of my name to GCI-STUDENTS.txt - in alphabetical order to what's already there.

### CODE REVIEW

**Comment by aadibajpai** [comment]
@Xu-Zijun sorry I accidentally merged this, please add the anagram to the existing GCI-STUDENTS.txt instead of making a new file

**Comment by Xu-Zijun** [comment]
I am unable to make a pull request and/or edit the existing "GCI-STUDENTS.txt".

**Comment by aadibajpai** [comment]
> I am unable to make a pull request and/or edit the existing "GCI-STUDENTS.txt".

Why not? You should be able to do it :)

**Comment by Xu-Zijun** [comment]
> > I am unable to make a pull request and/or edit the existing "GCI-STUDENTS.txt".
> 
> Why not? You should be able to do it :)

How do I do it?

**Comment by aadibajpai** [comment]
> > > I am unable to make a pull request and/or edit the existing "GCI-STUDENTS.txt".
> > 
> > 
> > Why not? You should be able to do it :)
> 
> How do I do it?

Go to the file and click the pencil icon

**Comment by Xu-Zijun** [comment]
> > > > I am unable to make a pull request and/or edit the existing "GCI-STUDENTS.txt".
> > > 
> > > 
> > > Why not? You should be able to do it :)
> > 
> > 
> > How do I do it?
> 
> Go to the file and click the pencil icon

Thanks

**Pull request merged**
